### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by magicoli** [d99kris/idntag#1]
Hello. Some dependencies are missing in installation instructions.

I had to install python3-taglib python3-acoustid and libtag1-dev to succeed.

So I guess the line
`sudo apt install python3-pip` 
should be
`sudo apt install python3-pip python3-taglib python3-acoustid libtag1-dev` 

Also I had to sudo the pip3 install commands

**Comment by d99kris** [comment]
Thanks @magicoli - I've updated the documentation now.

**Comment by gigawatts** [comment]
your testing scripts also require 'mp3info', so I recommend adding that to your dep list as well.

**Comment by d99kris** [comment]
Good suggestion - I've added the mp3info pre-requisite in 42916e4.
