### ISSUE TITLE
RFE: add support for cover art

### ISSUE THREAD

**Issue by cheese1** [d99kris/idntag#10]
would be great
musicbrainz has cover art archive for some releases
https://picard-docs.musicbrainz.org/en/config/options_cover_art_archive.html

**Comment by d99kris** [comment]
I've contemplated this feature request and concluded not to pursue it. 
I prefer to keep the scope of this tool to a minimum. Possibly - if someone provides a PR - we could add some support to exporting the detected id, to a text file or something, and then another separate tool/script could be created that reads that id and downloads cover art (or other data).

Will proceed to close this issue.
