### ISSUE TITLE
fedora-packages

### ISSUE THREAD

**Issue by cheese1** [d99kris/idntag#12]
i packaged idntag for fedora and plan to keep up with new versions as they get published

they can be downloaded at
https://www.nosuchhost.net/~cheese/fedora/packages/36/x86_64/idntag.html
this is for fedora 36 on x86_64

packages for aarch64 and other/older versions can be found from that page, too.

**Comment by d99kris** [comment]
Great, thanks :+1:  
I'll keep this issue open and will try to add some section to the README to link your page.
