### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by CrazyWolf13** [d99kris/idntag#15]
![image](https://user-images.githubusercontent.com/96661824/204084013-824ce194-986e-41e7-9c3c-8ffcd8f81080.png)

**Comment by d99kris** [comment]
Hi, I assume this is raspbian?

Did you run the pre-requisite commands listed in the README? In particular this one:
```
pip3 install pyacoustid pytaglib
```

**Comment by CrazyWolf13** [comment]
> Hi, I assume this is raspbian?
> 
> Did you run the pre-requisite commands listed in the README? In particular this one:
> 
> ```
> pip3 install pyacoustid pytaglib
> ```

I ran all those commands;
sudo apt install git cmake mp3info python3-pip libtag1-dev libchromaprint-dev libchromaprint-tools ffmpeg

git clone https://github.com/d99kris/idntag && cd idntag

mkdir -p build && cd build && cmake .. && make -s

ctest --output-on-failure (Here are four test failed)

**Comment by CrazyWolf13** [comment]
Oh i see i forgot the python ones thought they are as well for other users like the ubuntu.
Sorry my fault.

**Comment by CrazyWolf13** [comment]
> Hi, I assume this is raspbian?
> 
> Did you run the pre-requisite commands listed in the README? In particular this one:
> 
> ```
> pip3 install pyacoustid pytaglib
> ```

![image](https://user-images.githubusercontent.com/96661824/204087963-aa95f7ba-f2a9-4c0f-bdbc-ba82ac615cc7.png)
After installing the python prequisits the help page and everything popped up but as soon as i put in a path to my files this happend.

**Comment by d99kris** [comment]
Hm.. that looks like a bug..

Just to make sure it works for a "simple use case" could you help check that the tests pass now?
```
ctest --output-on-failure
```

I'll try check here later (not at a computer now). I see the music file looks like a YouTube downloaded file, would you be able to share the YouTube url?

**Comment by CrazyWolf13** [comment]
> Hm.. that looks like a bug..
> 
> Just to make sure it works for a "simple use case" could you help check that the tests pass now?
> 
> ```
> ctest --output-on-failure
> ```
> 
> I'll try check here later (not at a computer now). I see the music file looks like a YouTube downloaded file, would you be able to share the YouTube url?

Thanks for the quick response.
ctest didn't output any errors tests passed all.
I have a downloaded a playlist with yt-dlp and --embed-metadata (around 10 files)
One of the the files:
https://www.youtube.com/watch?v=4aoHDfa_8-s&list=PLbPRSq5YJU69JN5OKXzcCVcreBZhzPr4W&index=6

Most of the files are from this playlist: https://www.youtube.com/playlist?list=OLAK5uy_mwdWpg56m8E7xPSMQkMm9I_C8XLG_cY2E

**Comment by CrazyWolf13** [comment]
![image](https://user-images.githubusercontent.com/96661824/204088795-1e75c36c-e188-490e-8848-9fb92abd29bd.png)
After a reboot the first file went through without success sadly.

**Comment by d99kris** [comment]
> Thanks for the quick response. ctest didn't output any errors tests passed all. I have a downloaded a playlist with yt-dlp and --embed-metadata (around 10 files) One of the the files: https://www.youtube.com/watch?v=4aoHDfa_8-s&list=PLbPRSq5YJU69JN5OKXzcCVcreBZhzPr4W&index=6

Thanks, this is very useful input. I'll need to do some debugging here on my side, but unfortunately I cannot check today. Hopefully tomorrow.

**Comment by CrazyWolf13** [comment]
> > Thanks for the quick response. ctest didn't output any errors tests passed all. I have a downloaded a playlist with yt-dlp and --embed-metadata (around 10 files) One of the the files: https://www.youtube.com/watch?v=4aoHDfa_8-s&list=PLbPRSq5YJU69JN5OKXzcCVcreBZhzPr4W&index=6
> 
> Thanks, this is very useful input. I'll need to do some debugging here on my side, but unfortunately I cannot check today. Hopefully tomorrow.

No problem take your time, i have got a temporary fix with get_album_cover but it often fails cause yt-videos are not properly tagged

**Comment by d99kris** [comment]
Hi @CrazyWolf13 - in the above commit a fix has been implemented to gracefully handle the scenario when the music database returns invalid results. So there should be no more exception thrown by `idntag`.

However, the tracks you shared above are not in the `AcoustID` database, so they will unfortunately return `FAIL`.

**Comment by CrazyWolf13** [comment]
> Hi @CrazyWolf13 - in the above commit a fix has been implemented to gracefully handle the scenario when the music database returns invalid results. So there should be no more exception thrown by `idntag`.
> 
> However, the tracks you shared above are not in the `AcoustID` database, so they will unfortunately return `FAIL`. 

Thank you  very much for the fix.

Oh that's very sad.
Are there only the most know songs in this database?

**Comment by CrazyWolf13** [comment]
@d99kris 
I removed the idntag folder and reinstalled it. 
But I still get this :![Screenshot_20221127_091951_Termux.jpg](https://user-images.githubusercontent.com/96661824/204125675-726b22f9-c6be-4535-82c9-119c7910b35c.jpg)
Any ideas why? Or did I something wrong?

**Comment by d99kris** [comment]
> Any ideas why?

Did you do the install step?
```sudo make install```
(alternatively `./make.sh install`)

If yes and it's still not working, could you check what version `idntag -v` outputs?

**Comment by CrazyWolf13** [comment]
> > Any ideas why?
> 
> Did you do the install step?
> ```sudo make install```
> (alternatively `./make.sh install`)
> 
> If yes and it's still not working, could you check what version `idntag -v` outputs?

Great, it works now.
But sadly it didn't recognize any of my songs. So there is pretty much no use for me.

**Comment by d99kris** [comment]
> Oh that's very sad. Are there only the most know songs in this database?

To be honest, I am not very sure. There are other apps that are using the same library (pyacoustid) and the AcoustId database, so I would assume it has reasonable coverage. I've seen about 95% success in my usage, but I haven't used it a lot lately.

If I remember correctly the AcoustId database is to some extent based on user submissions, so its quality and coverage could depend a lot on how much users contribute.

**Comment by d99kris** [comment]
> Great, it works now. 

Ok, good!

> But sadly it didn't recognize any of my songs. So there is pretty much no use for me.

Ok, I understand 

Last time I researched databases/APIs for music identification, AcoustId was the only one that was free, so I went with it. Maybe there are other options now.
