### ISSUE TITLE
idntag scans working directory

### ISSUE THREAD

**Issue by CrazyWolf13** [d99kris/idntag#16]
idntag without path scans working directory which i suggest is not wanted.

**Comment by CrazyWolf13** [comment]
The least important issue lol

**Comment by d99kris** [comment]
Oh that sounds wrong. Will take a look.

**Comment by d99kris** [comment]
Hi again,
I'm not able to reproduce this. I get an error message when trying to run idntag without any path specified:
```
$ idntag 
usage: idntag [-h] [-k] [-l] [-v] path [path ...]
idntag: error: the following arguments are required: path
```

Could you please share how you run idntag when this happens?

**Comment by CrazyWolf13** [comment]
> Hi again,
> I'm not able to reproduce this. I get an error message when trying to run idntag without any path specified:
> ```
> $ idntag 
> usage: idntag [-h] [-k] [-l] [-v] path [path ...]
> idntag: error: the following arguments are required: path
> ```
> 
> Could you please share how you run idntag when this happens?

Hmm did you fix this as well? Yesterday it went through all my files in ~/ when i run idntag but now there is the message you sent above 🤷

**Comment by d99kris** [comment]
> Hmm did you fix this as well? Yesterday it went through all my files in ~/ when i run idntag but now there is the message you sent above 🤷

I don't think I changed anything related to the paths/argument processing, but I could be wrong. Anyway, thanks for sharing the latest test result. 👍
