### ISSUE TITLE
Output new assigned name

### ISSUE THREAD

**Issue by magicoli** [d99kris/idntag#2]
It would be very useful to output the renamed file path.
I need to manipulate the new file after it has been rename and as it is I have no way to know its new name.

**Comment by d99kris** [comment]
Thanks for the suggestion @magicoli - I've implemented support for it now. The output format on success is now:
```$ORGPATH : OK : $NEWPATH```
and for failure the format has been updated to:
```$ORGPATH : FAIL : $ERRORDETAILS```
