### ISSUE TITLE
Dont save music :(

### ISSUE THREAD

**Issue by dura0ok** [d99kris/idntag#6]
`/home/stepan7/Музыка/AC DC - Back In Black.mp3 : Traceback (most recent call last):
  File "./idntag", line 94, in <module>
    main()
  File "./idntag", line 90, in main
    identify_and_update_file(path, args.keepname)
  File "./idntag", line 53, in identify_and_update_file
    song.save()
  File "src/taglib.pyx", line 140, in taglib.File.save
AttributeError: 'NoneType' object has no attribute 'encode'
`

**Comment by d99kris** [comment]
Does `idntag` work for the example song in the package, i.e. something like this?
```
./idntag tests/song.mp3
```

Also can I check which OS/distro you are on?

And were the `idntag` dependencies listed in the README.md installed without issues?

Thanks.

**Comment by d99kris** [comment]
I cannot troubleshoot this further without more details of the use-case. I will proceed to close this issue for now.

Feel free to re-open and submit the requested information.
